version: '3.7'

volumes:
    data: {}

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.43.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    pid: "host"
    ports:
      - 8080:8080
    devices:
      - /dev/kmsg
    privileged: true
    ulimits:
      nproc: 65535
      nofile: 655535
    command: --logtostderr=true --housekeeping_interval="1s" --application_metrics_count_limit=1000 --disable_metrics=""
  server:
    build:
      context: .
    environment:
      - MAX_WORKERS=1
    ports:
      - 8000:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
